[package]
name = "blackjack_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.8.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"